# Generated by Django 5.0 on 2023-12-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colabEstac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="anios_premio",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="apellidos_colaborador",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="cc_banc_colaborador",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="cpostal_colaborador",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="direccion_colaborador",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="email1_colaborador",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="email2_colaborador",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="es_recibir_revista_obs",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="fech_naci_colaborador",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="localidad_colaborador",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="nombre_colaborador",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="provincia_colaborador",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="telefono1_colaborador",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="telefono2_colaborador",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
